# Elimina la infraestructura de Terraform en AWS
name: Terraform Destroy AWS Infra

on:
  # Configuramos que solo se pueda ejecutar manualmenteb
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# Ejecución de los trabajos
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      # Iniciar Terraform en el repositorio
      - name: Terraform Init
        id: init
        run: terraform init
      
      # Elimina infraestructura en AWS
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -var-file="actrafer.tfvars" -auto-approve
