# Workflow para validar que el c贸digo de Terraform es correcto
name: Terraform Validate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

# Ejecuci贸n de los trabajos
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
       
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      # Iniciar Terraform en el repositorio
      - name: Terraform Init
        id: init
        run: terraform init
      
       # Comprueba que la indexaci贸n y el c贸digo es correcto
      - name: Terraform fmt
        id: fmt
        run: terraform fmt
      
      # Valida
      - name: Terraform Validate
        id: validate
        run: terraform validate
